config_version: 0.4
genome_folder: /project/shefflab//deploy/plantref/genomes
genome_archive_folder: $GENOMES/archive
genome_archive_config: refgenie_config_archive.yaml
remote_url_base: https://refgenie.s3.amazonaws.com
genome_servers: ['http://refgenomes.databio.org']
genomes:
  a04927989a138483fe4e2ab06e12f710f79d95932dac38a3:
    aliases: ['Aureococcus_anophagefferens_JGI_1_0']
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: b962bd1ee2f7cb5f162d297cc9192675
            seek_keys:
              fasta: a04927989a138483fe4e2ab06e12f710f79d95932dac38a3.fa
              fai: a04927989a138483fe4e2ab06e12f710f79d95932dac38a3.fa.fai
              chrom_sizes: a04927989a138483fe4e2ab06e12f710f79d95932dac38a3.chrom.sizes
            asset_parents: []
            archive_digest: b3f79263dcbdeb9e2466a866664b0ded
            archive_size: 14.3MB
            asset_size: 54.9MB
            asset_children: []
        default_tag: default
    genome_description: Aureococcus anophagefferens JGI 1.0
    