config_version: 0.3
genome_folder: $GENOMES
genome_archive_folder: $GENOMES/archive
remote_url_base: https://refgenie.s3.amazonaws.com
genome_archive_config: master_archive.yaml
genome_servers: ['http://refgenomes.databio.org']
genomes:
  rCRSd:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: rCRSd.fa
              fai: rCRSd.fa.fai
              chrom_sizes: rCRSd.chrom.sizes
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            asset_parents: []
            archive_digest: 7b92449395ca9916e2fc1c98748f7203
            archive_size: 8.6KB
            asset_size: 41.4KB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: 32a37a52a377d95bfd4b3d66763e1396a4480f34ab5c318a
  hg38:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38.fa
              fai: hg38.fa.fai
              chrom_sizes: hg38.chrom.sizes
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            asset_parents: []
            archive_digest: 96d639d223b7310c8414e22138a9a375
            archive_size: 833.4MB
            asset_size: 2.9GB
            asset_children: []
        default_tag: default
      fasta_txome:
        asset_description: cDNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta_txome
            seek_keys:
              fasta_txome: hg38.fa
              fai: hg38.fa.fai
              chrom_sizes: hg38.chrom.sizes
            asset_digest: e452acaa6f4b4f28c29ce6e06beb07e0
            asset_parents: []
            archive_digest: 6e3ec595b501c382af879aca69b4eaf3
            archive_size: 69.1MB
            asset_size: 363.9MB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: b3422045db2293738bcb9973c1a0acdfabff3a0a3e1830bc
  hg38_cdna:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38_cdna.fa
              fai: hg38_cdna.fa.fai
              chrom_sizes: hg38_cdna.chrom.sizes
            asset_digest: e452acaa6f4b4f28c29ce6e06beb07e0
            asset_parents: []
            archive_digest: a96c0622acf58f2143dc9290897f2935
            archive_size: 69.1MB
            asset_size: 363.9MB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: b24ad420abde037e4995290ea8fdea2de6aa6576c2c0cc5d
  hg19:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg19.fa
              fai: hg19.fa.fai
              chrom_sizes: hg19.chrom.sizes
            asset_digest: 7ce3b03e30d6ef76af8c3ad09a141dfc
            asset_parents: []
            archive_digest: 1774fed53d5daee25e168b6f90b99186
            archive_size: 905.3MB
            asset_size: 3.0GB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: fb7002132265e88a91859e3c743fc7a898a057019fc11456
  hg18:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg18.fa
              fai: hg18.fa.fai
              chrom_sizes: hg18.chrom.sizes
            archive_digest: e7e899f1bc5bc42fe45f030cf0da5e5f
            archive_size: 899.7MB
            asset_size: 3.0GB
            asset_parents: []
            asset_children: []
            asset_digest: 0fc1d00b994befc9a00695b15b048af8
    genome_description: The
    genome_digest: 637e83a0492a1092720d640d6f7b6c89e05f8a73bff27c48
  hg38_noalt_decoy:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38_noalt_decoy.fa
              fai: hg38_noalt_decoy.fa.fai
              chrom_sizes: hg38_noalt_decoy.chrom.sizes
            archive_digest: 944ce1e0c2726f6520b0b872c32084b1
            archive_size: 835.0MB
            asset_size: 2.9GB
            asset_parents: []
            asset_children: []
            asset_digest: 3701eaccf6e8b6637a8b8384abfdc052
    genome_description: The
    genome_digest: 169c49ce7d61068a4dadf3fd6be030b3f6305f3ff8ba4e8d
  hg38_chr22:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38_chr22.fa
              fai: hg38_chr22.fa.fai
              chrom_sizes: hg38_chr22.chrom.sizes
            archive_digest: b13aaa02d427a107a3f7f06b7a73c82c
            archive_size: 11.7MB
            asset_size: 41.4MB
            asset_parents: []
            asset_children: ['hg38_chr22/hisat2_index:default', 'hg38_chr22/star_index:default', 'hg38_chr22/bismark_bt1_index:default', 'hg38_chr22/suffixerator_index:default']
            asset_digest: f197c1ac4b3e4c5dd013bd2021bb32e6
    genome_description: No description
    genome_digest: 201be65e4f4598f97a708c14124393e222f47ca609078f4f
  mouse_chrM2x:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: mouse_chrM2x.fa
              fai: mouse_chrM2x.fa.fai
              chrom_sizes: mouse_chrM2x.chrom.sizes
            archive_digest: d628219dc3439796dedd16209ebabe8c
            archive_size: 9.0KB
            asset_size: 38.3KB
            asset_parents: []
            asset_children: []
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
  hg38_mm10:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38_mm10.fa
              fai: hg38_mm10.fa.fai
              chrom_sizes: hg38_mm10.chrom.sizes
            archive_digest: 18128aad764c69ddf56e5ca60c3c6b57
            archive_size: 1.7GB
            asset_size: 5.5GB
            asset_parents: []
            asset_children: []
            asset_digest: 463540bce12ce47ae485f4430a5dbd29
    genome_description: Merged
    genome_digest: 7c8264246d3987b56b7a8bca2fb90bc5bf780d54c898a4e0
  dm6:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: dm6.fa
              fai: dm6.fa.fai
              chrom_sizes: dm6.chrom.sizes
            archive_digest: f1266a93d79e6359fdf982d6959a7765
            archive_size: 43.5MB
            asset_size: 139.0MB
            asset_parents: []
            asset_children: []
            asset_digest: 8620c745dbe7bfcdab89aacc155077db
    genome_description: Drosophila
    genome_digest: ffe91a81e875ed2264151d71d35404cbbea162889ee371d3
  hg19_cdna:
    genome_description: The
    genome_digest: 6b45ad5e3dfce38b39712e19008a4ff79e91c18769fe146b
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg19_cdna.fa
              fai: hg19_cdna.fa.fai
              chrom_sizes: hg19_cdna.chrom.sizes
            archive_digest: 9d747cef80a814657b9c8060df85b1e6
            archive_size: 60.7MB
            asset_size: 315.1MB
            asset_parents: []
            asset_children: []
            asset_digest: e146e5c1b8fd57b9f09ab46ec36adbad
  rn6:
    genome_description: No description
    genome_digest: No digest
  mm10:
    genome_description: No description
    genome_digest: No digest
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
  hg18_cdna:
    genome_description: The
    genome_digest: 2b0ab75f33466ebba2b87a196a60baff707eed19f8060672
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg18_cdna.fa
              fai: hg18_cdna.fa.fai
              chrom_sizes: hg18_cdna.chrom.sizes
            archive_digest: 54b3bf40c7813f5e837fc175ea504e4b
            archive_size: 26.4MB
            asset_size: 129.8MB
            asset_parents: []
            asset_children: []
            asset_digest: 456bf4dd716de36373539acf2595baf3
  hs38d1:
    genome_description: Decoy
    genome_digest: 5dc3e6688b41b347683a4b3fd6dac4bf6b21a5f562548f58
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
  human_rDNA:
    genome_description: No description
    genome_digest: No digest
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: human_rDNA.fa
              fai: human_rDNA.fa.fai
              chrom_sizes: human_rDNA.chrom.sizes
            archive_digest: fd8b9945334a7147fd61f72fb4e73b7f
            archive_size: 12.4KB
            asset_size: 48.7KB
            asset_parents: []
            asset_children: []
            asset_digest: null
  hg38_primary:
    genome_description: No description
    genome_digest: No digest
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
  human_alphasat:
    assets:
      fasta:
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: human_alphasat.fa
              fai: human_alphasat.fa.fai
              chrom_sizes: human_alphasat.chrom.sizes
            archive_digest: 3e28c7f456b21bb1c9fad74c9ab20ea0
            archive_size: 21.5KB
            asset_size: 107.4KB
            asset_parents: []
            asset_children: []
            asset_digest: 5b2d2705cff9c9315add79b3f0d793ad
  mm10_primary:
    genome_description: UCSC
    genome_digest: 7ec88fdeadfce0139622e812f0421c8966d84a28980a1602
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
  mm10_cdna:
    assets:
      fasta:
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: mm10_cdna.fa
              fai: mm10_cdna.fa.fai
              chrom_sizes: mm10_cdna.chrom.sizes
            archive_digest: 2b09de7b7b5b31fdc379fcb71e920ec3
            archive_size: 51.6MB
            asset_size: 247.6MB
            asset_parents: []
            asset_children: []
            asset_digest: 8192beb5916da1fdc5640b529fc7bb97
