config_version: 0.3
genome_folder: $GENOMES
genome_archive_folder: $GENOMES/archive
remote_url_base: https://refgenie.s3.amazonaws.com
genome_archive_config: master_archive.yaml
genome_servers: ['http://refgenomes.databio.org']
genomes:
  rCRSd:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: rCRSd.fa
              fai: rCRSd.fa.fai
              chrom_sizes: rCRSd.chrom.sizes
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            asset_parents: []
            archive_digest: ee6884dbd60991ce0b6f412852d44780
            archive_size: 8.6KB
            asset_size: 38.7KB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: 32a37a52a377d95bfd4b3d66763e1396a4480f34ab5c318a
  hg38:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38.fa
              fai: hg38.fa.fai
              chrom_sizes: hg38.chrom.sizes
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            asset_parents: []
            archive_digest: 96d639d223b7310c8414e22138a9a375
            archive_size: 833.4MB
            asset_size: 2.9GB
            asset_children: []
        default_tag: default
      fasta_txome:
        asset_description: cDNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta_txome
            seek_keys:
              fasta_txome: hg38.fa
              fai: hg38.fa.fai
              chrom_sizes: hg38.chrom.sizes
            asset_digest: e452acaa6f4b4f28c29ce6e06beb07e0
            asset_parents: []
            archive_digest: 6e3ec595b501c382af879aca69b4eaf3
            archive_size: 69.1MB
            asset_size: 363.9MB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: b3422045db2293738bcb9973c1a0acdfabff3a0a3e1830bc
  hg38_cdna:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg38_cdna.fa
              fai: hg38_cdna.fa.fai
              chrom_sizes: hg38_cdna.chrom.sizes
            asset_digest: e452acaa6f4b4f28c29ce6e06beb07e0
            asset_parents: []
            archive_digest: a96c0622acf58f2143dc9290897f2935
            archive_size: 69.1MB
            asset_size: 363.9MB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: b24ad420abde037e4995290ea8fdea2de6aa6576c2c0cc5d
  hg19:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: hg19.fa
              fai: hg19.fa.fai
              chrom_sizes: hg19.chrom.sizes
            asset_digest: 7ce3b03e30d6ef76af8c3ad09a141dfc
            asset_parents: []
            archive_digest: a62c387632d6e01aded715fe2197b9bd
            archive_size: 905.3MB
            asset_size: 3.0GB
            asset_children: []
        default_tag: default
    genome_description: The
    genome_digest: fb7002132265e88a91859e3c743fc7a898a057019fc11456
